//
//  StudentLocation.swift
//  On The Map
//
//  Created by Chuck Bradley on 4/7/15.
//  Copyright (c) 2015 FreedomMind. All rights reserved.
//

import Foundation
import MapKit

struct StudentLocation {
    
    // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    var id: String? = nil
    
    // an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account (user) id
    var uniqueKey:String? = nil

    // the first name of the student which matches their Udacity profile first name
    var firstName: String = ""

    // the last name of the student which matches their Udacity profile last name
    var lastName: String = ""
    
    // the location string used for geocoding the student location
    var mapString: String? = nil
    
    // the URL provided by the student
    var mediaURL: String? = nil
    
    // the latitude of the student location (ranges from -90 to 90)
    var latitude: Double? = nil
    
    // the longitude of the student location (ranges from -180 to 180)
    var longitude: Double? = nil
    
    // the annotation object used for the map view. The title stores the full name
    var annotation = MKPointAnnotation()


    // init with dictionary populated with (most of) the above values
    init(dictionary: [String: AnyObject]) {
        if let objectId = dictionary["objectId"] as? String {
            id = objectId
        }
        uniqueKey = dictionary["uniqueKey"] as? String
        if let fname = dictionary["firstName"] as? String { firstName = fname }
        if let lname = dictionary["lastName"] as? String { lastName = lname }
        mapString = dictionary["mapString"] as? String
        mediaURL = dictionary["mediaURL"] as? String
        if let lat = dictionary["latitude"] as? Double {
            if let long = dictionary["longitude"] as? Double {
                latitude = lat
                longitude = long
                let latDegrees = CLLocationDegrees(lat)
                let longDegrees = CLLocationDegrees(long)
                let coordinate = CLLocationCoordinate2D(latitude: latDegrees, longitude: longDegrees)
                
                annotation.coordinate = coordinate
                annotation.title = "\(firstName) \(lastName)"
                if let url = mediaURL {
                    annotation.subtitle = url
                }

            }
        }
    }



}